package com.drinkreminder.app.ui.theme

import androidx.compose.ui.graphics.Color

val WaterBlue = Color(0xFF2196F3)
val WaterBlueDark = Color(0xFF1976D2)
val WaterBlueLight = Color(0xFF64B5F6)
val WaterBlueSurface = Color(0xFFE3F2FD)

val md_theme_light_primary = Color(0xFF1565C0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C3A)
val md_theme_light_secondary = Color(0xFF545F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E3F8)
val md_theme_light_onSecondaryContainer = Color(0xFF111C2B)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFFA5C8FF)
val md_theme_dark_onPrimary = Color(0xFF00315E)
val md_theme_dark_primaryContainer = Color(0xFF004884)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_secondary = Color(0xFFBCC7DB)
val md_theme_dark_onSecondary = Color(0xFF263141)
val md_theme_dark_secondaryContainer = Color(0xFF3C4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E3F8)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)

val GoalMetGreen = Color(0xFF4CAF50)
val GoalPartialYellow = Color(0xFFFFC107)
val GoalNoneGray = Color(0xFFBDBDBD)
